### ISSUE TITLE
wrong parsing "recipient"  (my working code)

### ISSUE THREAD

**Issue by SANYA-SNEX** [php-mime-mail-parser/php-mime-mail-parser#40] opened 2015-02-17 11:26 UTC
function extract_email_address ($string) {
    foreach(preg_split('/\s/', $string) as $token) {
        $email = filter_var(filter_var($token, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL);
        if ($email !== false) {
            $emails[] = $email;
        }
    }
    return $emails;
}
//The check if a letter has many recipients
$address_array  = imap_rfc822_parse_adrlist($to, "example.com");
$from  = imap_rfc822_parse_adrlist($from, "example.com");
// check if my domain
$domain_base_array = array(
  'exemple1.com' => "my_1_domain",
  'exemple2.com' => "my_domainsecond",
  'exemple3.com' => "I_wner_of_letter",
 ); 

foreach ($address_array as $key_name => $value111){
$toaddres_host=$value111->host;
$toaddres_usr=$value111->mailbox;
$name=$value111->personal;
$decode = imap_mime_header_decode($text);
//$name=convert_chars($decode[0]->charset,$decode[0]->text);
$toaddres=$value111->mailbox."@".$value111->host;
$table_name = $domain_base_array[$toaddres_host];
if (isset($table_name)){
$ADRESSAT="yes";
}else{

$email_to=extract_email_address($Parser->parts[1][headers][received][0]);

$email_to_arr=explode('@', $email_to[0]);
$toaddres_usr=$email_to_arr[0];
$toaddres_host=$email_to_arr[1];
$toaddres=$email_to['0'];
$table_name = $domain_base_array[$toaddres_host];
if (isset($table_name)){
$ADRESSAT="yes";
}else{$ADRESSAT="not";}
}

**Comment by eXorus** [comment] 2015-02-17 12:23
Could you send me an email sample that didn't work ?

**Comment by SANYA-SNEX** [comment] 2015-02-17 13:09
problem extract all email and personal from "To" sections you can use this to parse http://php.net/manual/en/function.imap-mime-header-decode.php

**Comment by eXorus** [comment] 2016-03-20 16:41
Don't need to use that there is a better solution mailparse_rfc822_parse_addresses()
I'm closing this issue because this is a duplicate of #51

**Closed by eXorus** 2016-03-20 16:41 UTC
Labels: enhancement
