### ISSUE TITLE
Warning: input is not rfc822 compliant: not in < bracket

### ISSUE THREAD

**Issue by c1am** [php-mime-mail-parser/php-mime-mail-parser#393] opened 2022-06-16 17:25 UTC
I'm getting this error when trying to parse an email. Different parts will give different errors such as:
Warning: input is not rfc822 compliant: not in < bracket
Warning: input is not rfc822 compliant: already in < bracket

I'm wondering if there is a fix for this?

**Comment by eXorus** [comment] 2022-06-17 08:17
Duplicate of the discussion

**Closed by eXorus** 2022-06-17 08:17 UTC
Labels: bug
